//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RntCar.SDK.LogoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SatirBilgiAlanlar", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SatirBilgiAlanlar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Metarial_CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Metarial_DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Unit_CodeField;
        
        private double Unit_PriceField;
        
        private int QuantityField;
        
        private int Vat_RateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Auxil_CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Vatexcept_CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Vatexcept_ReasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Metarial_Code {
            get {
                return this.Metarial_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Metarial_CodeField, value) != true)) {
                    this.Metarial_CodeField = value;
                    this.RaisePropertyChanged("Metarial_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Metarial_Description {
            get {
                return this.Metarial_DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.Metarial_DescriptionField, value) != true)) {
                    this.Metarial_DescriptionField = value;
                    this.RaisePropertyChanged("Metarial_Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Unit_Code {
            get {
                return this.Unit_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Unit_CodeField, value) != true)) {
                    this.Unit_CodeField = value;
                    this.RaisePropertyChanged("Unit_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double Unit_Price {
            get {
                return this.Unit_PriceField;
            }
            set {
                if ((this.Unit_PriceField.Equals(value) != true)) {
                    this.Unit_PriceField = value;
                    this.RaisePropertyChanged("Unit_Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Vat_Rate {
            get {
                return this.Vat_RateField;
            }
            set {
                if ((this.Vat_RateField.Equals(value) != true)) {
                    this.Vat_RateField = value;
                    this.RaisePropertyChanged("Vat_Rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Auxil_Code {
            get {
                return this.Auxil_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Auxil_CodeField, value) != true)) {
                    this.Auxil_CodeField = value;
                    this.RaisePropertyChanged("Auxil_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Vatexcept_Code {
            get {
                return this.Vatexcept_CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.Vatexcept_CodeField, value) != true)) {
                    this.Vatexcept_CodeField = value;
                    this.RaisePropertyChanged("Vatexcept_Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Vatexcept_Reason {
            get {
                return this.Vatexcept_ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.Vatexcept_ReasonField, value) != true)) {
                    this.Vatexcept_ReasonField = value;
                    this.RaisePropertyChanged("Vatexcept_Reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaturaGeriDonusAlanlar", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class FaturaGeriDonusAlanlar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int FaturaRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaturaNumaraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int FaturaRef {
            get {
                return this.FaturaRefField;
            }
            set {
                if ((this.FaturaRefField.Equals(value) != true)) {
                    this.FaturaRefField = value;
                    this.RaisePropertyChanged("FaturaRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FaturaNumara {
            get {
                return this.FaturaNumaraField;
            }
            set {
                if ((object.ReferenceEquals(this.FaturaNumaraField, value) != true)) {
                    this.FaturaNumaraField = value;
                    this.RaisePropertyChanged("FaturaNumara");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Hata {
            get {
                return this.HataField;
            }
            set {
                if ((object.ReferenceEquals(this.HataField, value) != true)) {
                    this.HataField = value;
                    this.RaisePropertyChanged("Hata");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KrediKartiGeriDonusAlanlar", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class KrediKartiGeriDonusAlanlar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int KrediKartRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KrediKartNumaraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int KrediKartRef {
            get {
                return this.KrediKartRefField;
            }
            set {
                if ((this.KrediKartRefField.Equals(value) != true)) {
                    this.KrediKartRefField = value;
                    this.RaisePropertyChanged("KrediKartRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string KrediKartNumara {
            get {
                return this.KrediKartNumaraField;
            }
            set {
                if ((object.ReferenceEquals(this.KrediKartNumaraField, value) != true)) {
                    this.KrediKartNumaraField = value;
                    this.RaisePropertyChanged("KrediKartNumara");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Hata {
            get {
                return this.HataField;
            }
            set {
                if ((object.ReferenceEquals(this.HataField, value) != true)) {
                    this.HataField = value;
                    this.RaisePropertyChanged("Hata");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VirmanFisGeriDonusAlanlar", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class VirmanFisGeriDonusAlanlar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int VirmanFisRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VirmanNumaraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int VirmanFisRef {
            get {
                return this.VirmanFisRefField;
            }
            set {
                if ((this.VirmanFisRefField.Equals(value) != true)) {
                    this.VirmanFisRefField = value;
                    this.RaisePropertyChanged("VirmanFisRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string VirmanNumara {
            get {
                return this.VirmanNumaraField;
            }
            set {
                if ((object.ReferenceEquals(this.VirmanNumaraField, value) != true)) {
                    this.VirmanNumaraField = value;
                    this.RaisePropertyChanged("VirmanNumara");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Hata {
            get {
                return this.HataField;
            }
            set {
                if ((object.ReferenceEquals(this.HataField, value) != true)) {
                    this.HataField = value;
                    this.RaisePropertyChanged("Hata");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LogoService.RentGoServiceSoap")]
    public interface RentGoServiceSoap {
        
        // CODEGEN: Generating message contract since element name user_name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        RntCar.SDK.LogoService.LoginResponse Login(RntCar.SDK.LogoService.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<RntCar.SDK.LogoService.LoginResponse> LoginAsync(RntCar.SDK.LogoService.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Disconnect", ReplyAction="*")]
        bool Disconnect();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Disconnect", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DisconnectAsync();
        
        // CODEGEN: Generating message contract since element name ConnectResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Connect", ReplyAction="*")]
        RntCar.SDK.LogoService.ConnectResponse Connect(RntCar.SDK.LogoService.ConnectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Connect", ReplyAction="*")]
        System.Threading.Tasks.Task<RntCar.SDK.LogoService.ConnectResponse> ConnectAsync(RntCar.SDK.LogoService.ConnectRequest request);
        
        // CODEGEN: Generating message contract since element name CurrentFirmResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CurrentFirm", ReplyAction="*")]
        RntCar.SDK.LogoService.CurrentFirmResponse CurrentFirm(RntCar.SDK.LogoService.CurrentFirmRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CurrentFirm", ReplyAction="*")]
        System.Threading.Tasks.Task<RntCar.SDK.LogoService.CurrentFirmResponse> CurrentFirmAsync(RntCar.SDK.LogoService.CurrentFirmRequest request);
        
        // CODEGEN: Generating message contract since element name CurrentAccountCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CurrentAccountBalance", ReplyAction="*")]
        RntCar.SDK.LogoService.CurrentAccountBalanceResponse CurrentAccountBalance(RntCar.SDK.LogoService.CurrentAccountBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CurrentAccountBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<RntCar.SDK.LogoService.CurrentAccountBalanceResponse> CurrentAccountBalanceAsync(RntCar.SDK.LogoService.CurrentAccountBalanceRequest request);
        
        // CODEGEN: Generating message contract since element name tcno from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CurrentAccountCode", ReplyAction="*")]
        RntCar.SDK.LogoService.CurrentAccountCodeResponse CurrentAccountCode(RntCar.SDK.LogoService.CurrentAccountCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CurrentAccountCode", ReplyAction="*")]
        System.Threading.Tasks.Task<RntCar.SDK.LogoService.CurrentAccountCodeResponse> CurrentAccountCodeAsync(RntCar.SDK.LogoService.CurrentAccountCodeRequest request);
        
        // CODEGEN: Generating message contract since element name arp_code from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SalesInvoice", ReplyAction="*")]
        RntCar.SDK.LogoService.SalesInvoiceResponse SalesInvoice(RntCar.SDK.LogoService.SalesInvoiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SalesInvoice", ReplyAction="*")]
        System.Threading.Tasks.Task<RntCar.SDK.LogoService.SalesInvoiceResponse> SalesInvoiceAsync(RntCar.SDK.LogoService.SalesInvoiceRequest request);
        
        // CODEGEN: Generating message contract since element name date from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreditCardSlip", ReplyAction="*")]
        RntCar.SDK.LogoService.CreditCardSlipResponse CreditCardSlip(RntCar.SDK.LogoService.CreditCardSlipRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreditCardSlip", ReplyAction="*")]
        System.Threading.Tasks.Task<RntCar.SDK.LogoService.CreditCardSlipResponse> CreditCardSlipAsync(RntCar.SDK.LogoService.CreditCardSlipRequest request);
        
        // CODEGEN: Generating message contract since element name description from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemittanceSlip", ReplyAction="*")]
        RntCar.SDK.LogoService.RemittanceSlipResponse RemittanceSlip(RntCar.SDK.LogoService.RemittanceSlipRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemittanceSlip", ReplyAction="*")]
        System.Threading.Tasks.Task<RntCar.SDK.LogoService.RemittanceSlipResponse> RemittanceSlipAsync(RntCar.SDK.LogoService.RemittanceSlipRequest request);
        
        // CODEGEN: Generating message contract since element name FicheNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InvoicePdf", ReplyAction="*")]
        RntCar.SDK.LogoService.InvoicePdfResponse InvoicePdf(RntCar.SDK.LogoService.InvoicePdfRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InvoicePdf", ReplyAction="*")]
        System.Threading.Tasks.Task<RntCar.SDK.LogoService.InvoicePdfResponse> InvoicePdfAsync(RntCar.SDK.LogoService.InvoicePdfRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public RntCar.SDK.LogoService.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(RntCar.SDK.LogoService.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string user_password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int company_number;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string user_name, string user_password, int company_number) {
            this.user_name = user_name;
            this.user_password = user_password;
            this.company_number = company_number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public RntCar.SDK.LogoService.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(RntCar.SDK.LogoService.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConnectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Connect", Namespace="http://tempuri.org/", Order=0)]
        public RntCar.SDK.LogoService.ConnectRequestBody Body;
        
        public ConnectRequest() {
        }
        
        public ConnectRequest(RntCar.SDK.LogoService.ConnectRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ConnectRequestBody {
        
        public ConnectRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConnectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConnectResponse", Namespace="http://tempuri.org/", Order=0)]
        public RntCar.SDK.LogoService.ConnectResponseBody Body;
        
        public ConnectResponse() {
        }
        
        public ConnectResponse(RntCar.SDK.LogoService.ConnectResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConnectResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConnectResult;
        
        public ConnectResponseBody() {
        }
        
        public ConnectResponseBody(string ConnectResult) {
            this.ConnectResult = ConnectResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CurrentFirmRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CurrentFirm", Namespace="http://tempuri.org/", Order=0)]
        public RntCar.SDK.LogoService.CurrentFirmRequestBody Body;
        
        public CurrentFirmRequest() {
        }
        
        public CurrentFirmRequest(RntCar.SDK.LogoService.CurrentFirmRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CurrentFirmRequestBody {
        
        public CurrentFirmRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CurrentFirmResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CurrentFirmResponse", Namespace="http://tempuri.org/", Order=0)]
        public RntCar.SDK.LogoService.CurrentFirmResponseBody Body;
        
        public CurrentFirmResponse() {
        }
        
        public CurrentFirmResponse(RntCar.SDK.LogoService.CurrentFirmResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CurrentFirmResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CurrentFirmResult;
        
        public CurrentFirmResponseBody() {
        }
        
        public CurrentFirmResponseBody(string CurrentFirmResult) {
            this.CurrentFirmResult = CurrentFirmResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CurrentAccountBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CurrentAccountBalance", Namespace="http://tempuri.org/", Order=0)]
        public RntCar.SDK.LogoService.CurrentAccountBalanceRequestBody Body;
        
        public CurrentAccountBalanceRequest() {
        }
        
        public CurrentAccountBalanceRequest(RntCar.SDK.LogoService.CurrentAccountBalanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CurrentAccountBalanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CurrentAccountCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tcno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string taxno;
        
        public CurrentAccountBalanceRequestBody() {
        }
        
        public CurrentAccountBalanceRequestBody(string CurrentAccountCode, string tcno, string taxno) {
            this.CurrentAccountCode = CurrentAccountCode;
            this.tcno = tcno;
            this.taxno = taxno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CurrentAccountBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CurrentAccountBalanceResponse", Namespace="http://tempuri.org/", Order=0)]
        public RntCar.SDK.LogoService.CurrentAccountBalanceResponseBody Body;
        
        public CurrentAccountBalanceResponse() {
        }
        
        public CurrentAccountBalanceResponse(RntCar.SDK.LogoService.CurrentAccountBalanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CurrentAccountBalanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double CurrentAccountBalanceResult;
        
        public CurrentAccountBalanceResponseBody() {
        }
        
        public CurrentAccountBalanceResponseBody(double CurrentAccountBalanceResult) {
            this.CurrentAccountBalanceResult = CurrentAccountBalanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CurrentAccountCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CurrentAccountCode", Namespace="http://tempuri.org/", Order=0)]
        public RntCar.SDK.LogoService.CurrentAccountCodeRequestBody Body;
        
        public CurrentAccountCodeRequest() {
        }
        
        public CurrentAccountCodeRequest(RntCar.SDK.LogoService.CurrentAccountCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CurrentAccountCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tcno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string taxno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string customer_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string customer_last_name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string address2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string telephone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string city;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string town;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string country;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string tax_office;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string efaturaemailadr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string specode1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string specode2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string specode3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string specode4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string specode5;
        
        public CurrentAccountCodeRequestBody() {
        }
        
        public CurrentAccountCodeRequestBody(
                    string tcno, 
                    string taxno, 
                    string customer_name, 
                    string customer_last_name, 
                    string title, 
                    string address, 
                    string address2, 
                    string telephone, 
                    string email, 
                    string city, 
                    string town, 
                    string country, 
                    string tax_office, 
                    string efaturaemailadr, 
                    string specode1, 
                    string specode2, 
                    string specode3, 
                    string specode4, 
                    string specode5) {
            this.tcno = tcno;
            this.taxno = taxno;
            this.customer_name = customer_name;
            this.customer_last_name = customer_last_name;
            this.title = title;
            this.address = address;
            this.address2 = address2;
            this.telephone = telephone;
            this.email = email;
            this.city = city;
            this.town = town;
            this.country = country;
            this.tax_office = tax_office;
            this.efaturaemailadr = efaturaemailadr;
            this.specode1 = specode1;
            this.specode2 = specode2;
            this.specode3 = specode3;
            this.specode4 = specode4;
            this.specode5 = specode5;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CurrentAccountCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CurrentAccountCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public RntCar.SDK.LogoService.CurrentAccountCodeResponseBody Body;
        
        public CurrentAccountCodeResponse() {
        }
        
        public CurrentAccountCodeResponse(RntCar.SDK.LogoService.CurrentAccountCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CurrentAccountCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CurrentAccountCodeResult;
        
        public CurrentAccountCodeResponseBody() {
        }
        
        public CurrentAccountCodeResponseBody(string CurrentAccountCodeResult) {
            this.CurrentAccountCodeResult = CurrentAccountCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SalesInvoiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SalesInvoice", Namespace="http://tempuri.org/", Order=0)]
        public RntCar.SDK.LogoService.SalesInvoiceRequestBody Body;
        
        public SalesInvoiceRequest() {
        }
        
        public SalesInvoiceRequest(RntCar.SDK.LogoService.SalesInvoiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SalesInvoiceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arp_code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string doc_track_no;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string doc_number;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string invoice_date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int warehouse;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string note;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string note2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string note3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string note4;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string tcno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string taxno;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public int division;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string project_code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public RntCar.SDK.LogoService.SatirBilgiAlanlar[] LineList;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string arp_code_shpm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string vatexcept_Code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string vatexcept_Reason;
        
        public SalesInvoiceRequestBody() {
        }
        
        public SalesInvoiceRequestBody(
                    string arp_code, 
                    string doc_track_no, 
                    string doc_number, 
                    string invoice_date, 
                    int warehouse, 
                    string note, 
                    string note2, 
                    string note3, 
                    string note4, 
                    string tcno, 
                    string taxno, 
                    int division, 
                    string project_code, 
                    RntCar.SDK.LogoService.SatirBilgiAlanlar[] LineList, 
                    string arp_code_shpm, 
                    string vatexcept_Code, 
                    string vatexcept_Reason) {
            this.arp_code = arp_code;
            this.doc_track_no = doc_track_no;
            this.doc_number = doc_number;
            this.invoice_date = invoice_date;
            this.warehouse = warehouse;
            this.note = note;
            this.note2 = note2;
            this.note3 = note3;
            this.note4 = note4;
            this.tcno = tcno;
            this.taxno = taxno;
            this.division = division;
            this.project_code = project_code;
            this.LineList = LineList;
            this.arp_code_shpm = arp_code_shpm;
            this.vatexcept_Code = vatexcept_Code;
            this.vatexcept_Reason = vatexcept_Reason;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SalesInvoiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SalesInvoiceResponse", Namespace="http://tempuri.org/", Order=0)]
        public RntCar.SDK.LogoService.SalesInvoiceResponseBody Body;
        
        public SalesInvoiceResponse() {
        }
        
        public SalesInvoiceResponse(RntCar.SDK.LogoService.SalesInvoiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SalesInvoiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RntCar.SDK.LogoService.FaturaGeriDonusAlanlar[] SalesInvoiceResult;
        
        public SalesInvoiceResponseBody() {
        }
        
        public SalesInvoiceResponseBody(RntCar.SDK.LogoService.FaturaGeriDonusAlanlar[] SalesInvoiceResult) {
            this.SalesInvoiceResult = SalesInvoiceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreditCardSlipRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreditCardSlip", Namespace="http://tempuri.org/", Order=0)]
        public RntCar.SDK.LogoService.CreditCardSlipRequestBody Body;
        
        public CreditCardSlipRequest() {
        }
        
        public CreditCardSlipRequest(RntCar.SDK.LogoService.CreditCardSlipRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreditCardSlipRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int division;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string note1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string note2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string arp_code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string bank_code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string proje_code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string doc_number;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public double credit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string approvenr;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public bool canceled_status;
        
        public CreditCardSlipRequestBody() {
        }
        
        public CreditCardSlipRequestBody(string date, int division, string note1, string note2, string arp_code, string bank_code, string proje_code, string doc_number, string description, double credit, string approvenr, bool canceled_status) {
            this.date = date;
            this.division = division;
            this.note1 = note1;
            this.note2 = note2;
            this.arp_code = arp_code;
            this.bank_code = bank_code;
            this.proje_code = proje_code;
            this.doc_number = doc_number;
            this.description = description;
            this.credit = credit;
            this.approvenr = approvenr;
            this.canceled_status = canceled_status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreditCardSlipResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreditCardSlipResponse", Namespace="http://tempuri.org/", Order=0)]
        public RntCar.SDK.LogoService.CreditCardSlipResponseBody Body;
        
        public CreditCardSlipResponse() {
        }
        
        public CreditCardSlipResponse(RntCar.SDK.LogoService.CreditCardSlipResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreditCardSlipResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RntCar.SDK.LogoService.KrediKartiGeriDonusAlanlar[] CreditCardSlipResult;
        
        public CreditCardSlipResponseBody() {
        }
        
        public CreditCardSlipResponseBody(RntCar.SDK.LogoService.KrediKartiGeriDonusAlanlar[] CreditCardSlipResult) {
            this.CreditCardSlipResult = CreditCardSlipResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemittanceSlipRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemittanceSlip", Namespace="http://tempuri.org/", Order=0)]
        public RntCar.SDK.LogoService.RemittanceSlipRequestBody Body;
        
        public RemittanceSlipRequest() {
        }
        
        public RemittanceSlipRequest(RntCar.SDK.LogoService.RemittanceSlipRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemittanceSlipRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double total;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int division;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string iyzico_arp_code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string custemer_arp_code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string proje_code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string specode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string line_description;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public bool canceled_status;
        
        public RemittanceSlipRequestBody() {
        }
        
        public RemittanceSlipRequestBody(string description, string date, double total, int division, string iyzico_arp_code, string custemer_arp_code, string proje_code, string specode, string line_description, bool canceled_status) {
            this.description = description;
            this.date = date;
            this.total = total;
            this.division = division;
            this.iyzico_arp_code = iyzico_arp_code;
            this.custemer_arp_code = custemer_arp_code;
            this.proje_code = proje_code;
            this.specode = specode;
            this.line_description = line_description;
            this.canceled_status = canceled_status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemittanceSlipResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemittanceSlipResponse", Namespace="http://tempuri.org/", Order=0)]
        public RntCar.SDK.LogoService.RemittanceSlipResponseBody Body;
        
        public RemittanceSlipResponse() {
        }
        
        public RemittanceSlipResponse(RntCar.SDK.LogoService.RemittanceSlipResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemittanceSlipResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RntCar.SDK.LogoService.VirmanFisGeriDonusAlanlar[] RemittanceSlipResult;
        
        public RemittanceSlipResponseBody() {
        }
        
        public RemittanceSlipResponseBody(RntCar.SDK.LogoService.VirmanFisGeriDonusAlanlar[] RemittanceSlipResult) {
            this.RemittanceSlipResult = RemittanceSlipResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvoicePdfRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvoicePdf", Namespace="http://tempuri.org/", Order=0)]
        public RntCar.SDK.LogoService.InvoicePdfRequestBody Body;
        
        public InvoicePdfRequest() {
        }
        
        public InvoicePdfRequest(RntCar.SDK.LogoService.InvoicePdfRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InvoicePdfRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FicheNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AccountTitle;
        
        public InvoicePdfRequestBody() {
        }
        
        public InvoicePdfRequestBody(string FicheNo, string AccountTitle) {
            this.FicheNo = FicheNo;
            this.AccountTitle = AccountTitle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvoicePdfResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvoicePdfResponse", Namespace="http://tempuri.org/", Order=0)]
        public RntCar.SDK.LogoService.InvoicePdfResponseBody Body;
        
        public InvoicePdfResponse() {
        }
        
        public InvoicePdfResponse(RntCar.SDK.LogoService.InvoicePdfResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InvoicePdfResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] InvoicePdfResult;
        
        public InvoicePdfResponseBody() {
        }
        
        public InvoicePdfResponseBody(byte[] InvoicePdfResult) {
            this.InvoicePdfResult = InvoicePdfResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RentGoServiceSoapChannel : RntCar.SDK.LogoService.RentGoServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RentGoServiceSoapClient : System.ServiceModel.ClientBase<RntCar.SDK.LogoService.RentGoServiceSoap>, RntCar.SDK.LogoService.RentGoServiceSoap {
        
        public RentGoServiceSoapClient() {
        }
        
        public RentGoServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RentGoServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RentGoServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RentGoServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RntCar.SDK.LogoService.LoginResponse RntCar.SDK.LogoService.RentGoServiceSoap.Login(RntCar.SDK.LogoService.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string user_name, string user_password, int company_number) {
            RntCar.SDK.LogoService.LoginRequest inValue = new RntCar.SDK.LogoService.LoginRequest();
            inValue.Body = new RntCar.SDK.LogoService.LoginRequestBody();
            inValue.Body.user_name = user_name;
            inValue.Body.user_password = user_password;
            inValue.Body.company_number = company_number;
            RntCar.SDK.LogoService.LoginResponse retVal = ((RntCar.SDK.LogoService.RentGoServiceSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RntCar.SDK.LogoService.LoginResponse> RntCar.SDK.LogoService.RentGoServiceSoap.LoginAsync(RntCar.SDK.LogoService.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<RntCar.SDK.LogoService.LoginResponse> LoginAsync(string user_name, string user_password, int company_number) {
            RntCar.SDK.LogoService.LoginRequest inValue = new RntCar.SDK.LogoService.LoginRequest();
            inValue.Body = new RntCar.SDK.LogoService.LoginRequestBody();
            inValue.Body.user_name = user_name;
            inValue.Body.user_password = user_password;
            inValue.Body.company_number = company_number;
            return ((RntCar.SDK.LogoService.RentGoServiceSoap)(this)).LoginAsync(inValue);
        }
        
        public bool Disconnect() {
            return base.Channel.Disconnect();
        }
        
        public System.Threading.Tasks.Task<bool> DisconnectAsync() {
            return base.Channel.DisconnectAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RntCar.SDK.LogoService.ConnectResponse RntCar.SDK.LogoService.RentGoServiceSoap.Connect(RntCar.SDK.LogoService.ConnectRequest request) {
            return base.Channel.Connect(request);
        }
        
        public string Connect() {
            RntCar.SDK.LogoService.ConnectRequest inValue = new RntCar.SDK.LogoService.ConnectRequest();
            inValue.Body = new RntCar.SDK.LogoService.ConnectRequestBody();
            RntCar.SDK.LogoService.ConnectResponse retVal = ((RntCar.SDK.LogoService.RentGoServiceSoap)(this)).Connect(inValue);
            return retVal.Body.ConnectResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RntCar.SDK.LogoService.ConnectResponse> RntCar.SDK.LogoService.RentGoServiceSoap.ConnectAsync(RntCar.SDK.LogoService.ConnectRequest request) {
            return base.Channel.ConnectAsync(request);
        }
        
        public System.Threading.Tasks.Task<RntCar.SDK.LogoService.ConnectResponse> ConnectAsync() {
            RntCar.SDK.LogoService.ConnectRequest inValue = new RntCar.SDK.LogoService.ConnectRequest();
            inValue.Body = new RntCar.SDK.LogoService.ConnectRequestBody();
            return ((RntCar.SDK.LogoService.RentGoServiceSoap)(this)).ConnectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RntCar.SDK.LogoService.CurrentFirmResponse RntCar.SDK.LogoService.RentGoServiceSoap.CurrentFirm(RntCar.SDK.LogoService.CurrentFirmRequest request) {
            return base.Channel.CurrentFirm(request);
        }
        
        public string CurrentFirm() {
            RntCar.SDK.LogoService.CurrentFirmRequest inValue = new RntCar.SDK.LogoService.CurrentFirmRequest();
            inValue.Body = new RntCar.SDK.LogoService.CurrentFirmRequestBody();
            RntCar.SDK.LogoService.CurrentFirmResponse retVal = ((RntCar.SDK.LogoService.RentGoServiceSoap)(this)).CurrentFirm(inValue);
            return retVal.Body.CurrentFirmResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RntCar.SDK.LogoService.CurrentFirmResponse> RntCar.SDK.LogoService.RentGoServiceSoap.CurrentFirmAsync(RntCar.SDK.LogoService.CurrentFirmRequest request) {
            return base.Channel.CurrentFirmAsync(request);
        }
        
        public System.Threading.Tasks.Task<RntCar.SDK.LogoService.CurrentFirmResponse> CurrentFirmAsync() {
            RntCar.SDK.LogoService.CurrentFirmRequest inValue = new RntCar.SDK.LogoService.CurrentFirmRequest();
            inValue.Body = new RntCar.SDK.LogoService.CurrentFirmRequestBody();
            return ((RntCar.SDK.LogoService.RentGoServiceSoap)(this)).CurrentFirmAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RntCar.SDK.LogoService.CurrentAccountBalanceResponse RntCar.SDK.LogoService.RentGoServiceSoap.CurrentAccountBalance(RntCar.SDK.LogoService.CurrentAccountBalanceRequest request) {
            return base.Channel.CurrentAccountBalance(request);
        }
        
        public double CurrentAccountBalance(string CurrentAccountCode, string tcno, string taxno) {
            RntCar.SDK.LogoService.CurrentAccountBalanceRequest inValue = new RntCar.SDK.LogoService.CurrentAccountBalanceRequest();
            inValue.Body = new RntCar.SDK.LogoService.CurrentAccountBalanceRequestBody();
            inValue.Body.CurrentAccountCode = CurrentAccountCode;
            inValue.Body.tcno = tcno;
            inValue.Body.taxno = taxno;
            RntCar.SDK.LogoService.CurrentAccountBalanceResponse retVal = ((RntCar.SDK.LogoService.RentGoServiceSoap)(this)).CurrentAccountBalance(inValue);
            return retVal.Body.CurrentAccountBalanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RntCar.SDK.LogoService.CurrentAccountBalanceResponse> RntCar.SDK.LogoService.RentGoServiceSoap.CurrentAccountBalanceAsync(RntCar.SDK.LogoService.CurrentAccountBalanceRequest request) {
            return base.Channel.CurrentAccountBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<RntCar.SDK.LogoService.CurrentAccountBalanceResponse> CurrentAccountBalanceAsync(string CurrentAccountCode, string tcno, string taxno) {
            RntCar.SDK.LogoService.CurrentAccountBalanceRequest inValue = new RntCar.SDK.LogoService.CurrentAccountBalanceRequest();
            inValue.Body = new RntCar.SDK.LogoService.CurrentAccountBalanceRequestBody();
            inValue.Body.CurrentAccountCode = CurrentAccountCode;
            inValue.Body.tcno = tcno;
            inValue.Body.taxno = taxno;
            return ((RntCar.SDK.LogoService.RentGoServiceSoap)(this)).CurrentAccountBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RntCar.SDK.LogoService.CurrentAccountCodeResponse RntCar.SDK.LogoService.RentGoServiceSoap.CurrentAccountCode(RntCar.SDK.LogoService.CurrentAccountCodeRequest request) {
            return base.Channel.CurrentAccountCode(request);
        }
        
        public string CurrentAccountCode(
                    string tcno, 
                    string taxno, 
                    string customer_name, 
                    string customer_last_name, 
                    string title, 
                    string address, 
                    string address2, 
                    string telephone, 
                    string email, 
                    string city, 
                    string town, 
                    string country, 
                    string tax_office, 
                    string efaturaemailadr, 
                    string specode1, 
                    string specode2, 
                    string specode3, 
                    string specode4, 
                    string specode5) {
            RntCar.SDK.LogoService.CurrentAccountCodeRequest inValue = new RntCar.SDK.LogoService.CurrentAccountCodeRequest();
            inValue.Body = new RntCar.SDK.LogoService.CurrentAccountCodeRequestBody();
            inValue.Body.tcno = tcno;
            inValue.Body.taxno = taxno;
            inValue.Body.customer_name = customer_name;
            inValue.Body.customer_last_name = customer_last_name;
            inValue.Body.title = title;
            inValue.Body.address = address;
            inValue.Body.address2 = address2;
            inValue.Body.telephone = telephone;
            inValue.Body.email = email;
            inValue.Body.city = city;
            inValue.Body.town = town;
            inValue.Body.country = country;
            inValue.Body.tax_office = tax_office;
            inValue.Body.efaturaemailadr = efaturaemailadr;
            inValue.Body.specode1 = specode1;
            inValue.Body.specode2 = specode2;
            inValue.Body.specode3 = specode3;
            inValue.Body.specode4 = specode4;
            inValue.Body.specode5 = specode5;
            RntCar.SDK.LogoService.CurrentAccountCodeResponse retVal = ((RntCar.SDK.LogoService.RentGoServiceSoap)(this)).CurrentAccountCode(inValue);
            return retVal.Body.CurrentAccountCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RntCar.SDK.LogoService.CurrentAccountCodeResponse> RntCar.SDK.LogoService.RentGoServiceSoap.CurrentAccountCodeAsync(RntCar.SDK.LogoService.CurrentAccountCodeRequest request) {
            return base.Channel.CurrentAccountCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<RntCar.SDK.LogoService.CurrentAccountCodeResponse> CurrentAccountCodeAsync(
                    string tcno, 
                    string taxno, 
                    string customer_name, 
                    string customer_last_name, 
                    string title, 
                    string address, 
                    string address2, 
                    string telephone, 
                    string email, 
                    string city, 
                    string town, 
                    string country, 
                    string tax_office, 
                    string efaturaemailadr, 
                    string specode1, 
                    string specode2, 
                    string specode3, 
                    string specode4, 
                    string specode5) {
            RntCar.SDK.LogoService.CurrentAccountCodeRequest inValue = new RntCar.SDK.LogoService.CurrentAccountCodeRequest();
            inValue.Body = new RntCar.SDK.LogoService.CurrentAccountCodeRequestBody();
            inValue.Body.tcno = tcno;
            inValue.Body.taxno = taxno;
            inValue.Body.customer_name = customer_name;
            inValue.Body.customer_last_name = customer_last_name;
            inValue.Body.title = title;
            inValue.Body.address = address;
            inValue.Body.address2 = address2;
            inValue.Body.telephone = telephone;
            inValue.Body.email = email;
            inValue.Body.city = city;
            inValue.Body.town = town;
            inValue.Body.country = country;
            inValue.Body.tax_office = tax_office;
            inValue.Body.efaturaemailadr = efaturaemailadr;
            inValue.Body.specode1 = specode1;
            inValue.Body.specode2 = specode2;
            inValue.Body.specode3 = specode3;
            inValue.Body.specode4 = specode4;
            inValue.Body.specode5 = specode5;
            return ((RntCar.SDK.LogoService.RentGoServiceSoap)(this)).CurrentAccountCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RntCar.SDK.LogoService.SalesInvoiceResponse RntCar.SDK.LogoService.RentGoServiceSoap.SalesInvoice(RntCar.SDK.LogoService.SalesInvoiceRequest request) {
            return base.Channel.SalesInvoice(request);
        }
        
        public RntCar.SDK.LogoService.FaturaGeriDonusAlanlar[] SalesInvoice(
                    string arp_code, 
                    string doc_track_no, 
                    string doc_number, 
                    string invoice_date, 
                    int warehouse, 
                    string note, 
                    string note2, 
                    string note3, 
                    string note4, 
                    string tcno, 
                    string taxno, 
                    int division, 
                    string project_code, 
                    RntCar.SDK.LogoService.SatirBilgiAlanlar[] LineList, 
                    string arp_code_shpm, 
                    string vatexcept_Code, 
                    string vatexcept_Reason) {
            RntCar.SDK.LogoService.SalesInvoiceRequest inValue = new RntCar.SDK.LogoService.SalesInvoiceRequest();
            inValue.Body = new RntCar.SDK.LogoService.SalesInvoiceRequestBody();
            inValue.Body.arp_code = arp_code;
            inValue.Body.doc_track_no = doc_track_no;
            inValue.Body.doc_number = doc_number;
            inValue.Body.invoice_date = invoice_date;
            inValue.Body.warehouse = warehouse;
            inValue.Body.note = note;
            inValue.Body.note2 = note2;
            inValue.Body.note3 = note3;
            inValue.Body.note4 = note4;
            inValue.Body.tcno = tcno;
            inValue.Body.taxno = taxno;
            inValue.Body.division = division;
            inValue.Body.project_code = project_code;
            inValue.Body.LineList = LineList;
            inValue.Body.arp_code_shpm = arp_code_shpm;
            inValue.Body.vatexcept_Code = vatexcept_Code;
            inValue.Body.vatexcept_Reason = vatexcept_Reason;
            RntCar.SDK.LogoService.SalesInvoiceResponse retVal = ((RntCar.SDK.LogoService.RentGoServiceSoap)(this)).SalesInvoice(inValue);
            return retVal.Body.SalesInvoiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RntCar.SDK.LogoService.SalesInvoiceResponse> RntCar.SDK.LogoService.RentGoServiceSoap.SalesInvoiceAsync(RntCar.SDK.LogoService.SalesInvoiceRequest request) {
            return base.Channel.SalesInvoiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<RntCar.SDK.LogoService.SalesInvoiceResponse> SalesInvoiceAsync(
                    string arp_code, 
                    string doc_track_no, 
                    string doc_number, 
                    string invoice_date, 
                    int warehouse, 
                    string note, 
                    string note2, 
                    string note3, 
                    string note4, 
                    string tcno, 
                    string taxno, 
                    int division, 
                    string project_code, 
                    RntCar.SDK.LogoService.SatirBilgiAlanlar[] LineList, 
                    string arp_code_shpm, 
                    string vatexcept_Code, 
                    string vatexcept_Reason) {
            RntCar.SDK.LogoService.SalesInvoiceRequest inValue = new RntCar.SDK.LogoService.SalesInvoiceRequest();
            inValue.Body = new RntCar.SDK.LogoService.SalesInvoiceRequestBody();
            inValue.Body.arp_code = arp_code;
            inValue.Body.doc_track_no = doc_track_no;
            inValue.Body.doc_number = doc_number;
            inValue.Body.invoice_date = invoice_date;
            inValue.Body.warehouse = warehouse;
            inValue.Body.note = note;
            inValue.Body.note2 = note2;
            inValue.Body.note3 = note3;
            inValue.Body.note4 = note4;
            inValue.Body.tcno = tcno;
            inValue.Body.taxno = taxno;
            inValue.Body.division = division;
            inValue.Body.project_code = project_code;
            inValue.Body.LineList = LineList;
            inValue.Body.arp_code_shpm = arp_code_shpm;
            inValue.Body.vatexcept_Code = vatexcept_Code;
            inValue.Body.vatexcept_Reason = vatexcept_Reason;
            return ((RntCar.SDK.LogoService.RentGoServiceSoap)(this)).SalesInvoiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RntCar.SDK.LogoService.CreditCardSlipResponse RntCar.SDK.LogoService.RentGoServiceSoap.CreditCardSlip(RntCar.SDK.LogoService.CreditCardSlipRequest request) {
            return base.Channel.CreditCardSlip(request);
        }
        
        public RntCar.SDK.LogoService.KrediKartiGeriDonusAlanlar[] CreditCardSlip(string date, int division, string note1, string note2, string arp_code, string bank_code, string proje_code, string doc_number, string description, double credit, string approvenr, bool canceled_status) {
            RntCar.SDK.LogoService.CreditCardSlipRequest inValue = new RntCar.SDK.LogoService.CreditCardSlipRequest();
            inValue.Body = new RntCar.SDK.LogoService.CreditCardSlipRequestBody();
            inValue.Body.date = date;
            inValue.Body.division = division;
            inValue.Body.note1 = note1;
            inValue.Body.note2 = note2;
            inValue.Body.arp_code = arp_code;
            inValue.Body.bank_code = bank_code;
            inValue.Body.proje_code = proje_code;
            inValue.Body.doc_number = doc_number;
            inValue.Body.description = description;
            inValue.Body.credit = credit;
            inValue.Body.approvenr = approvenr;
            inValue.Body.canceled_status = canceled_status;
            RntCar.SDK.LogoService.CreditCardSlipResponse retVal = ((RntCar.SDK.LogoService.RentGoServiceSoap)(this)).CreditCardSlip(inValue);
            return retVal.Body.CreditCardSlipResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RntCar.SDK.LogoService.CreditCardSlipResponse> RntCar.SDK.LogoService.RentGoServiceSoap.CreditCardSlipAsync(RntCar.SDK.LogoService.CreditCardSlipRequest request) {
            return base.Channel.CreditCardSlipAsync(request);
        }
        
        public System.Threading.Tasks.Task<RntCar.SDK.LogoService.CreditCardSlipResponse> CreditCardSlipAsync(string date, int division, string note1, string note2, string arp_code, string bank_code, string proje_code, string doc_number, string description, double credit, string approvenr, bool canceled_status) {
            RntCar.SDK.LogoService.CreditCardSlipRequest inValue = new RntCar.SDK.LogoService.CreditCardSlipRequest();
            inValue.Body = new RntCar.SDK.LogoService.CreditCardSlipRequestBody();
            inValue.Body.date = date;
            inValue.Body.division = division;
            inValue.Body.note1 = note1;
            inValue.Body.note2 = note2;
            inValue.Body.arp_code = arp_code;
            inValue.Body.bank_code = bank_code;
            inValue.Body.proje_code = proje_code;
            inValue.Body.doc_number = doc_number;
            inValue.Body.description = description;
            inValue.Body.credit = credit;
            inValue.Body.approvenr = approvenr;
            inValue.Body.canceled_status = canceled_status;
            return ((RntCar.SDK.LogoService.RentGoServiceSoap)(this)).CreditCardSlipAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RntCar.SDK.LogoService.RemittanceSlipResponse RntCar.SDK.LogoService.RentGoServiceSoap.RemittanceSlip(RntCar.SDK.LogoService.RemittanceSlipRequest request) {
            return base.Channel.RemittanceSlip(request);
        }
        
        public RntCar.SDK.LogoService.VirmanFisGeriDonusAlanlar[] RemittanceSlip(string description, string date, double total, int division, string iyzico_arp_code, string custemer_arp_code, string proje_code, string specode, string line_description, bool canceled_status) {
            RntCar.SDK.LogoService.RemittanceSlipRequest inValue = new RntCar.SDK.LogoService.RemittanceSlipRequest();
            inValue.Body = new RntCar.SDK.LogoService.RemittanceSlipRequestBody();
            inValue.Body.description = description;
            inValue.Body.date = date;
            inValue.Body.total = total;
            inValue.Body.division = division;
            inValue.Body.iyzico_arp_code = iyzico_arp_code;
            inValue.Body.custemer_arp_code = custemer_arp_code;
            inValue.Body.proje_code = proje_code;
            inValue.Body.specode = specode;
            inValue.Body.line_description = line_description;
            inValue.Body.canceled_status = canceled_status;
            RntCar.SDK.LogoService.RemittanceSlipResponse retVal = ((RntCar.SDK.LogoService.RentGoServiceSoap)(this)).RemittanceSlip(inValue);
            return retVal.Body.RemittanceSlipResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RntCar.SDK.LogoService.RemittanceSlipResponse> RntCar.SDK.LogoService.RentGoServiceSoap.RemittanceSlipAsync(RntCar.SDK.LogoService.RemittanceSlipRequest request) {
            return base.Channel.RemittanceSlipAsync(request);
        }
        
        public System.Threading.Tasks.Task<RntCar.SDK.LogoService.RemittanceSlipResponse> RemittanceSlipAsync(string description, string date, double total, int division, string iyzico_arp_code, string custemer_arp_code, string proje_code, string specode, string line_description, bool canceled_status) {
            RntCar.SDK.LogoService.RemittanceSlipRequest inValue = new RntCar.SDK.LogoService.RemittanceSlipRequest();
            inValue.Body = new RntCar.SDK.LogoService.RemittanceSlipRequestBody();
            inValue.Body.description = description;
            inValue.Body.date = date;
            inValue.Body.total = total;
            inValue.Body.division = division;
            inValue.Body.iyzico_arp_code = iyzico_arp_code;
            inValue.Body.custemer_arp_code = custemer_arp_code;
            inValue.Body.proje_code = proje_code;
            inValue.Body.specode = specode;
            inValue.Body.line_description = line_description;
            inValue.Body.canceled_status = canceled_status;
            return ((RntCar.SDK.LogoService.RentGoServiceSoap)(this)).RemittanceSlipAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RntCar.SDK.LogoService.InvoicePdfResponse RntCar.SDK.LogoService.RentGoServiceSoap.InvoicePdf(RntCar.SDK.LogoService.InvoicePdfRequest request) {
            return base.Channel.InvoicePdf(request);
        }
        
        public byte[] InvoicePdf(string FicheNo, string AccountTitle) {
            RntCar.SDK.LogoService.InvoicePdfRequest inValue = new RntCar.SDK.LogoService.InvoicePdfRequest();
            inValue.Body = new RntCar.SDK.LogoService.InvoicePdfRequestBody();
            inValue.Body.FicheNo = FicheNo;
            inValue.Body.AccountTitle = AccountTitle;
            RntCar.SDK.LogoService.InvoicePdfResponse retVal = ((RntCar.SDK.LogoService.RentGoServiceSoap)(this)).InvoicePdf(inValue);
            return retVal.Body.InvoicePdfResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RntCar.SDK.LogoService.InvoicePdfResponse> RntCar.SDK.LogoService.RentGoServiceSoap.InvoicePdfAsync(RntCar.SDK.LogoService.InvoicePdfRequest request) {
            return base.Channel.InvoicePdfAsync(request);
        }
        
        public System.Threading.Tasks.Task<RntCar.SDK.LogoService.InvoicePdfResponse> InvoicePdfAsync(string FicheNo, string AccountTitle) {
            RntCar.SDK.LogoService.InvoicePdfRequest inValue = new RntCar.SDK.LogoService.InvoicePdfRequest();
            inValue.Body = new RntCar.SDK.LogoService.InvoicePdfRequestBody();
            inValue.Body.FicheNo = FicheNo;
            inValue.Body.AccountTitle = AccountTitle;
            return ((RntCar.SDK.LogoService.RentGoServiceSoap)(this)).InvoicePdfAsync(inValue);
        }
    }
}
